extends Node

# warning-ignore:unused_signal
#signal player_health_changed(hearts)
signal player_has_landed_on_ground(color)
# warning-ignore:unused_signal
signal player_has_landed_on_enemy()
# warning-ignore:unused_signal
signal player_score_changed(amount)
# warning-ignore:unused_signal
signal player_coin_amount_changed(amount)
# warning-ignore:unused_signal
signal player_touched_paint()
# warning-ignore:unused_signal
signal player_picked_up_item(type)
# warning-ignore:unused_signal
signal player_finished_easy()
# warning-ignore:unused_signal
signal player_finished_medium()
# warning-ignore:unused_signal
signal on_orb_pickup(orb_id)
# warning-ignore:unused_signal
signal debuff_applied()
# warning-ignore:unused_signal
signal on_red_button_pressed()
# warning-ignore:unused_signal
signal player_stat_changed()
# warning-ignore:unused_signal
signal color_changed(new_color)
